### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by Seomzo** [danikhan632/Auto-GPT-AlpacaTrader-Plugin#10]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 96, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 142, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
  File "/app/autogpt/plugins.py", line 227, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
  File "<frozen zipimport>", line 284, in load_module
  File "<frozen zipimport>", line 779, in _get_module_code
zipimport.ZipImportError: can't find module '.'
PS C:\Users\alsad\Autogpt1\Auto-GPT-0.4.0\Auto-GPT-0.4.0>

**Comment by danikhan632** [comment]
just fixed thanks for the heads up
