### ISSUE TITLE
Getting TypeError when trying to run Auto-GPT with AlpacaTrader Plugin

### ISSUE THREAD

**Issue by wurkin** [danikhan632/Auto-GPT-AlpacaTrader-Plugin#13]
this is the error I am getting. Installed everything fresh in a python virtual environment and still get this.

`TypeError: Can't instantiate abstract class AutoGPTAlpacaTraderPlugin with abstract methods can_handle_text_embedding, handle_text_embedding`

**Comment by LedburyStudios** [comment]
yeah, same error here:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ledhe\Desktop\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\ledhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ledhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\ledhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ledhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ledhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ledhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ledhe\Desktop\Auto-GPT\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\Users\ledhe\Desktop\Auto-GPT\autogpt\main.py", line 142, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ledhe\Desktop\Auto-GPT\autogpt\plugins.py", line 238, in scan_plugins
    loaded_plugins.append(a_module())
                          ^^^^^^^^^^
  File "C:\Users\ledhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\abstract_singleton\__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class AutoGPTAlpacaTraderPlugin with abstract methods can_handle_text_embedding, handle_text_embedding`

**Comment by LedburyStudios** [comment]
I have added this to the __init__.py located at src/

`def can_handle_text_embedding(self) -> bool:
        pass
    def handle_text_embedding(self) -> bool:
        pass`

not sure if its going to break somthing but it got me past this error

**Comment by danikhan632** [comment]
fixed issue, apologies about the delay

**Comment by LedburyStudios** [comment]
> fixed issue, apologies about the delay

Line 278 just needs a : on the end

/src/auto_gpt_alpacatrader_plugin/__init__.py


thanks for fixing

**Comment by danikhan632** [comment]
thanks idk how I missed that

**Comment by LedburyStudios** [comment]
Easy mistake mate, keep smashing it
