### ISSUE TITLE
Failed to load Auto-GPT-AlpacaTrader-Plugin/src/auto_gpt_alpacatrader_plugin

### ISSUE THREAD

**Issue by TheCyberWarlock** [danikhan632/Auto-GPT-AlpacaTrader-Plugin#19]
Unable to load plugin, followed guide in the readme. Getting this error when running AutoGPT;

Failed to load Auto-GPT-AlpacaTrader-Plugin/src/auto_gpt_alpacatrader_plugin
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.app.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/app/cli.py", line 121, in main
    run_auto_gpt(
  File "/app/autogpt/app/main.py", line 136, in run_auto_gpt
    config.plugins = scan_plugins(config, config.debug_mode)
  File "/app/autogpt/plugins/__init__.py", line 266, in scan_plugins
    for key in dir(zipped_module):
UnboundLocalError: local variable 'zipped_module' referenced before assignment

**Comment by dimileeh** [comment]
Not sure about your traceback, but using the latest `stable` AutoGPT code with this plugin, I also encountered
`Failed to load Auto-GPT-AlpacaTrader-Plugin/src/auto_gpt_alpacatrader_plugin`.

After adding the `Exception` message into the print statement, I found out that I lacked 2 `pip` packages in my environment: `yfinance` and `datapackage`. After installing them using `pip install yfinance datapackage`, the Alpaca plugin loaded fine.
